source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

use_frameworks!

target 'LearnWords' do

pod 'Alamofire'
pod 'RxCocoa'
pod 'RxSwift'
pod 'RxOptional'
#pod 'RealmSwift', '~>10'
pod 'RealmSwift'

end